# Generated by Django 4.2.5 on 2023-09-28 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_director'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_model', models.CharField(max_length=2)),
                ('robot_version', models.CharField(max_length=2)),
                ('quantity', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
